---
# similar to scikit-learn .codecov.yml
# coverage:
#   status:
#     project:
#       default:
#         # Commits pushed to main should not make the overall
#         # project coverage decrease by more than 1%:
#         target: auto
#         threshold: 1%
#     patch:
#       default:
#         # Be tolerant on slight code coverage diff on PRs to limit
#         # noisy red coverage status on github PRs.
#         target: auto
#         threshold: 1%
comment:                  # this is a top-level key
  layout: reach, diff, flags, files
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

ignore:
- '*/tests/'    # ignore folders related to testing
- '*/data/'
