[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "wonkyconn"
description = "Evaluating the residual motion in fMRI connectome and visualise reports."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [{ name = "Hao-Ting Wang", email = "htwangtw@gmail.com" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dynamic = ["version"]
dependencies = [
  "numpy",
  "scipy",
  "patsy",
  "pandas>=2.0",
  "rich",
  "numba",
  "seaborn",
  "matplotlib",
  "statsmodels",
  "tqdm",
  "nibabel",
  "nilearn",
  "brainspace",
]

[project.scripts]
wonkyconn = "wonkyconn.run:main"

[project.urls]
"Homepage" = "https://github.com/HALFpipe/wonkyconn"
"Documentation" = "https://wonkyconn.readthedocs.io/en/latest/"

[project.optional-dependencies]
textual = ["textual>=0.58"]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
    "myst-parser>=5.1.0", # >= 5.1.0 for the GitHub-like callout boxes
    "sphinx-argparse",
]
dev = [
    "ruff",
    "pre-commit",
    "mypy",
    "pandas-stubs",
    "types-tqdm",
    "pytest",
    "pytest-cov",
]

[tool.pixi.workspace]
channels = ["conda-forge", "https://conda.fmri.science"]
platforms = ["linux-64", "osx-arm64"]

[tool.pixi.environments]
default = { features = ["dev", "editable", "test"], solve-group = "default" }
docs = { features = ["docs", "editable"], solve-group = "default" }
test = { features = ["editable", "test"], solve-group = "default" }
# Use "wonkyconn" feature for production environment, so it is identifiable
wonkyconn = { features = ["production"], solve-group = "production" }

[tool.pixi.dependencies]
numpy = "*"
scipy = "*"
patsy = "*"
pandas = ">=2.0"
rich = "*"
numba = "*"
seaborn = "*"
matplotlib-base = "*"
statsmodels = "*"
tqdm = "*"
nibabel = "*"
brainspace = "*"
textual = "*"

[tool.pixi.feature.editable.pypi-dependencies]
wonkyconn = { path = ".", editable = true }

[tool.pixi.feature.production.pypi-dependencies]
wonkyconn = { path = ".", editable = false }

[tool.pixi.feature.test.dependencies]
nibabel = "*"
nilearn = "*"
pytest = "*"
pytest-cov = "*"
templateflow = "*"

p7zip = "*"
datalad = ">=1.0"

[tool.pixi.feature.test.tasks]
lint = { cmd = "pre-commit run --all-files" }
unittest = { cmd = "pytest -s --cov=wonkyconn --cov-report=xml --pyargs wonkyconn -m 'not heavy_smoke and not smoke'" }
fulltest = { cmd = "pytest -s --cov=wonkyconn --cov-report=xml --pyargs wonkyconn -m 'not smoke'" }  # only run the heavy smoke tests
smoketestlight = { cmd = "pytest -s --cov=wonkyconn --cov-report=xml --pyargs wonkyconn -m smoke" }  # only run the light smoke tests

[tool.pixi.feature.docs.dependencies]
sphinx = "*"
sphinx_rtd_theme = "*"
myst-parser = "*"
sphinx-argparse = "*"

[tool.pixi.feature.dev.dependencies]
act = ">=0.2.82"
ruff = "*"
pre-commit = "*"
mypy = "*"
pandas-stubs = "*"
types-tqdm = "*"
textual = "*"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0+ci" # Fallback version for CI

[tool.hatch.build.hooks.vcs]
version-file = "wonkyconn/_version.py"

[tool.hatch.build.targets.sdist]
exclude = [".git_archival.txt"]

[tool.hatch.build.targets.wheel]
packages = ["wonkyconn"]
exclude = [".github"]

[tool.ruff]
line-length = 127

[tool.ruff.lint]
select = [
  "F", # pyflakes
  "E", # pycodestyle
  "W", # pycodestyle
  "I", # isort
  "B", # bugbears
  "N", # pep8-naming
]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
enable_error_code = ["ignore-without-code", "redundant-expr"] # "truthy-bool"
no_implicit_optional = true
show_error_codes = true
# strict = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "bids.*",
  "brainspace.*",
  "datalad.*",
  "joblib",
  "matplotlib.*",
  "nilearn",
  "nilearn.*",
  "numba.*",
  "patsy.*",
  "rich.*",
  "scipy.*",
  "seaborn.*",
  "sklearn.*",
  "statsmodels.*",
  "templateflow.*",
  "nibabel.*",
]

[[tool.mypy.overrides]]
ignore_errors = true
module = ["wonkyconn.tests.*", "conf", "subject-network-overlap"]

[tool.pytest.ini_options]
markers = [
  "smoke: smoke tests that will run on a simulated dataset (deselect with '-m \"not smoke\"')",
  "heavy_smoke: smoke tests that will with the prediction and gradient metrics (deselect with '-m \"not heavy_smoke\"')",
]
# filterwarnings = ["error"]
minversion = "7"
log_cli_level = "INFO"
xfail_strict = true
testpaths = ["wonkyconn/tests"]
addopts = [
  "-ra",
  "--strict-config",
  "--strict-markers",
  "--doctest-modules",
  "-v",
]
