on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["*"]
    paths:
      - "Dockerfile"
      - "pixi.lock"
      - ".github/workflows/docker.yml"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  docker-build:
    runs-on: self-hosted
    steps:
      - name: Set up environment
        run: |
          git config --global user.name "halfpipe"
          git config --global user.email "halfpipe@fmri.science"
          git config --global datalad.runtime.max-annex-jobs "$(nproc)"
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476
        with:
          condarc: |
            channels:
              - conda-forge
          environment-name: datalad
          create-args: >-
            datalad
          cache-environment: true
          init-shell: bash

      - id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf
        with:
          images: halfpipe/wonkyconn
          tags: |
            type=edge,branch=main
            type=pep440,pattern={{version}}

      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
        id: buildx
      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: wonky:conn
          load: true
      # always use light mode for testing container since the full version was tested during build
      - run: |
          datalad get data/halfpipe data/atlases
          docker run --rm \
            --mount="type=bind,source=${{ github.workspace }},target=${{ github.workspace }}" \
            --workdir="${{ github.workspace }}" \
            wonky:conn \
            --phenotypes data/halfpipe/participants.tsv \
            --atlas Schaefer2018Combined data/atlases/atlas-Schaefer2018Combined_dseg.nii.gz \
            --light-mode \
            data/halfpipe test group

      - uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2
        # PRs from forks don't have access to secrets, disable this step in that case.
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        if: github.event_name != 'pull_request'
        with:
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: true
