name: Tests

on:
  push:
    branches:
      - main
      - maint/*
    tags:
      - "*"
  pull_request:
    branches:
      - main
      - maint/*
    paths: ["wonkyconn/**", "pyproject.toml", "pixi.lock", "Dockerfile"]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      heavy-tests-required: ${{ steps.filter.outputs.heavy-metrics }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            heavy-metrics:
              - 'wonkyconn/features/calculate_gradients_correlation.py'
              - 'wonkyconn/features/age_sex_prediction.py'
              - 'wonkyconn/tests/test_gradients_correlation.py'
              - 'wonkyconn/tests/test_cli.py'

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          git config --global user.name "halfpipe"
          git config --global user.email "halfpipe@fmri.science"
          git config --global datalad.runtime.max-annex-jobs "$(nproc)"
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/cache@v5
        with:
          path: ~/.cache/templateflow
          key: templateflow
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0
        with:
          pixi-version: v0.53.0
          cache: true
          environments: test
          frozen: true
      - run: pixi run unittest
      - run: pixi run smoketestlight
      - uses: codecov/codecov-action@v6
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  heavy-smoke-tests:
    needs: [detect-changes]
    if: needs.detect-changes.outputs.heavy-tests-required == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          git config --global user.name "halfpipe"
          git config --global user.email "halfpipe@fmri.science"
          git config --global datalad.runtime.max-annex-jobs "$(nproc)"
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/cache@v5
        with:
          path: ~/.cache/templateflow
          key: templateflow
      - uses: prefix-dev/setup-pixi@1b2de7f3351f171c8b4dfeb558c639cb58ed4ec0
        with:
          pixi-version: v0.53.0
          cache: true
          environments: test
          frozen: true
      - run: pixi run fulltest
      - uses: codecov/codecov-action@v6
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload generated figures
        uses: actions/upload-artifact@v7
        with:
          name: figures
          path: figures_artifacts/**/*.png
